import { Component } from '@angular/core';
import { MarketingPageComponent } from './marketing-page';

@Component({
  standalone: true,
  imports: [MarketingPageComponent],
  template: `<app-marketing-page title="About MediSphere" [paragraphs]="paragraphs" />`,
})
export class AboutComponent {
  paragraphs = [
    'MediSphere Cognitive Twin is a healthcare intelligence platform exploring how digital twins, federated AI models, and FHIR interoperability can support proactive, personalized care.',
    'Patient records, vitals and model outputs are generated by the platform services so every screen can be explored end to end.',
  ];
}

@Component({
  standalone: true,
  imports: [MarketingPageComponent],
  template: `<app-marketing-page title="Platform Features" [paragraphs]="paragraphs" />`,
})
export class FeaturesComponent {
  paragraphs = [
    'Patient 360 with longitudinal timeline, vitals, labs, conditions, medications, and FHIR resources.',
    'Digital Health Twin with body-region visualization and risk heatmaps.',
    'Cardiovascular and diabetes risk models with SHAP-style explainability.',
    'Real-time vitals streaming simulation with configurable alert rules.',
    'AI-assisted care plan generation with mandatory doctor review and sign-off.',
    'Federated learning dashboard, audit logging, consent management, and population health analytics.',
  ];
}

@Component({
  standalone: true,
  imports: [MarketingPageComponent],
  template: `<app-marketing-page title="How It Works" [paragraphs]="paragraphs" />`,
})
export class HowItWorksComponent {
  paragraphs = [
    'Step 1: FHIR resources are ingested, validated, and stored in the patient twin store.',
    'Step 2: Wearable vitals stream through Kafka-style topics into the monitoring pipeline.',
    'Step 3: Federated risk models produce predictions with confidence scores and feature contributions.',
    'Step 4: Clinicians review alerts, approve care plans, and track adherence and outcomes.',
  ];
}

@Component({
  standalone: true,
  imports: [MarketingPageComponent],
  template: `<app-marketing-page title="Security & Privacy" [paragraphs]="paragraphs" />`,
})
export class SecurityComponent {
  paragraphs = [
    'JWT authentication, role-based access control, bcrypt password hashing, and audit logging of sensitive actions.',
    'Kafka-ready vitals streaming, FHIR R4 resource validation, and consent verification on sensitive operations.',
    'This prototype implements a security architecture and is NOT certified for HIPAA or clinical production use.',
  ];
}

@Component({
  standalone: true,
  imports: [MarketingPageComponent],
  template: `<app-marketing-page title="Contact" [paragraphs]="paragraphs" />`,
})
export class ContactComponent {
  paragraphs = [
    'This is a demonstration project. For details see the docs folder: README, ARCHITECTURE, SECURITY, FHIR, AI_ML, DEPLOYMENT, DEMO.',
    'Support: demo@medisphere.local.',
  ];
}
